version: '3'

services:

  redis:
    image: redis

  mongo:
    image: mongo

  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - "8081:8081"
    command: flask run --port 8081 --host 0.0.0.0
    volumes:
      - ./src:/home/kanban/src/
      - .env:/home/kanban/.env
    environment:
      KANBAN_ENV_FILE: ${KANBAN_ENV_FILE:-/home/kanban/.env}
    links:
      - redis
      - mongo

  worker:
    build:
      context: .
      dockerfile: docker/worker.dockerfile
    command: celery worker -A app.celery -l info
    volumes:
      - ./src:/home/kanban/src/
      - .env:/home/kanban/.env
    environment:
      KANBAN_ENV_FILE: ${KANBAN_ENV_FILE:-/home/kanban/.env}
    links:
      - redis
      - mongo